name: catatanku
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
# local depedencies
  auth:
    path: auth
  core:
    path: core
  note:
    path: note
  flutter:
    sdk: flutter

# remote depedencies
  firebase_core: ^3.12.1
  flutter_bloc: ^9.1.0
  go_router: ^14.8.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
