// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzHEF0Gz4n0YKkoeo1jvoEoIaj9o-3_4I',
    appId: '1:248931051464:web:ba563b0be85128d747c2fd',
    messagingSenderId: '248931051464',
    projectId: 'catatanku-f3c71',
    authDomain: 'catatanku-f3c71.firebaseapp.com',
    storageBucket: 'catatanku-f3c71.firebasestorage.app',
    measurementId: 'G-8CRQ44Q9KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDABm-ObM6zmI8TDkIxrln_jz7E5qTcmIE',
    appId: '1:248931051464:android:cc9589ca525c161947c2fd',
    messagingSenderId: '248931051464',
    projectId: 'catatanku-f3c71',
    storageBucket: 'catatanku-f3c71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzJeEzci-gwyK6GTxmNMmTaJyJqns9_Gk',
    appId: '1:248931051464:ios:e6f6d6c0ef79ca6a47c2fd',
    messagingSenderId: '248931051464',
    projectId: 'catatanku-f3c71',
    storageBucket: 'catatanku-f3c71.firebasestorage.app',
    iosBundleId: 'com.example.catatanku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzJeEzci-gwyK6GTxmNMmTaJyJqns9_Gk',
    appId: '1:248931051464:ios:e6f6d6c0ef79ca6a47c2fd',
    messagingSenderId: '248931051464',
    projectId: 'catatanku-f3c71',
    storageBucket: 'catatanku-f3c71.firebasestorage.app',
    iosBundleId: 'com.example.catatanku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzHEF0Gz4n0YKkoeo1jvoEoIaj9o-3_4I',
    appId: '1:248931051464:web:036692eb276020df47c2fd',
    messagingSenderId: '248931051464',
    projectId: 'catatanku-f3c71',
    authDomain: 'catatanku-f3c71.firebaseapp.com',
    storageBucket: 'catatanku-f3c71.firebasestorage.app',
    measurementId: 'G-EDJ0BP1K96',
  );
}
